[workspace]
channels = ["conda-forge"]
name = "5150_Analytics"
platforms = ["win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]

[environments]
nb = ["py", "nb", "datasci", "ffmpeg"]
manim = ["py10", "nb", "datasci", "ffmpeg", "manim"]

[feature.py10.dependencies]
python = "3.10.*"

[feature.py.dependencies]
python = "*"

[feature.manim.dependencies]
manim = "*"

[feature.nb.dependencies]
notebook = "*"
nbconvert = "*"
markdown = "*"
lxml = "*"
pygments = "*"
pymdown-extensions = "*"

[feature.datasci.dependencies]
pandas = "*"
scikit-learn = "*"
scikit-image = "*"
seaborn = "*"
sqlalchemy = "*"
psycopg = "*"
openpyxl = "*"

[feature.datasci.pypi-dependencies]
pyedgar = { path = "../../../Programming/Python/pyedgar", editable = true }
reslib = { path = "../../../Programming/Python/reslib", editable = true }

[feature.ffmpeg.dependencies]
ffmpeg = ">=7.1.1,<8"
